name: "Infrastructure - Prod"

on:
  push:
    branches: [main]
    paths: [infra/**]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  prod:
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra/svc-blob-storage
      environment: prod
      project_name: blobdemo
      service_name: svc-blob-storage
    secrets: inherit
