name: "Infrastructure - QA"

on:
  push:
    branches: [main]
    paths: [infra/**]
  pull_request:
    paths: [infra/**]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  qa:
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra/svc-blob-storage
      environment: qa
      project_name: blobdemo
      service_name: svc-blob-storage
    secrets: inherit
