name: Infrastructure

on:
  push:
    branches: [main]
    paths: [infra/**]
  pull_request:
    paths: [infra/**]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  dev:
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra
      environment: dev
      project_name: blobdemo
      service_name: svc-blob-storage
    secrets: inherit

  qa:
    needs: [dev]
    if: github.ref == 'refs/heads/main'
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra
      environment: qa
      project_name: blobdemo
      service_name: svc-blob-storage
    secrets: inherit
