name: Infrastructure

on:
  push:
    branches: [main]
    paths: [infra/**]
  pull_request:
    paths: [infra/**]
  workflow_dispatch:
    inputs:
      action:
        description: "What to do?"
        type: choice
        default: plan
        options:
          - plan
          - apply
          - destroy-plan
          - destroy

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  dev:
    uses: PixelTech-Solutions/Terraform/.github/workflows/terraform.yml@main
    with:
      working_directory: ./infra
      environment: dev
      backend_resource_group: rg-terraform-state
      backend_storage_account: stpixeltechstate
      backend_container: tfstate
      backend_key: "svc-blob-storage-example/dev/terraform.tfstate"
      additional_args: "-var-file=environments/dev.tfvars"
      action: ${{ github.event.inputs.action || 'plan' }}
    secrets: inherit
